stages:
  - build

variables:
  CGO_ENABLED: 0
  GOARCH: amd64
  REPO_NAME: github.com/egeneralov/glauth

docker:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_BUILDKIT: 1
  script:
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
    - docker build --pull -t "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA}" .
    - docker push "${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}-${CI_COMMIT_SHA}"
  except:
    - tags

docker-tag:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker build --pull -t "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}" .
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
    - docker push "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
  only:
    - tags

helm-tag:
  image: registry.gitlab.com/egeneralov/aio-bundle:3.3.1
  stage: build
  script:
    - 'sed -i "s/version.*/version: ${CI_COMMIT_TAG}/g" .helm/glauth/Chart.yaml'
    - 'sed -i "s/appVersion.*/appVersion: ${CI_COMMIT_TAG}/g" .helm/glauth/Chart.yaml'
    - 'sed -i "s/tag: .*/tag: ${CI_COMMIT_TAG}/g" .helm/glauth/values.yaml'
    - 'helm init --client-only'
    - 'helm lint .helm/glauth'
    - 'helm template .helm/glauth | kubeval --strict'
    - 'helm package .helm/glauth'
  artifacts:
    paths:
      - glauth-*.tgz
  only:
    - tags



.build: &build
  image: golang:1.12.9-alpine
  stage: build
  before_script:
    - apk add --no-cache make git
    - go get -u github.com/jteeuwen/go-bindata/...
    - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
    - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
    - cd $GOPATH/src/$REPO_NAME
    - export GO111MODULE=on
  script:
    - ls -lha
    - go mod download
    - /go/bin/go-bindata -pkg=main assets .
    - make ${CI_JOB_NAME}
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/bin/glauth-${CI_JOB_NAME}
    when: on_success
    expire_in: 180 days

linux32:
  <<: *build
linux64:
  <<: *build
linuxarm32:
  <<: *build
linuxarm64:
  <<: *build
darwin64:
  <<: *build
win32:
  <<: *build
win64:
  <<: *build
